name: Extract metadata about a Cabal project

outputs:
  cabal-file: ${{steps.find-cabal.outputs.file}}
  name: ${{steps.resolve-name.outputs.name}}
  version: ${{steps.resolve-version.outputs.version}}

runs:
  using: composite
  steps:
    - id: find-cabal
      run: |
        files=(*.cabal)
        if [ "${#files[@]}" -ne 1 ]
        then
          echo "More than 1 cabal file"
          exit 1
        fi
        file=${files[0]}
        echo "::set-output name=file::$file"
    - id: resolve-version
      run: |
        version="$(grep -oP '^version:\s*\K.*' ${{steps.find-cabal.outputs.file}})"
        echo "::set-output name=version::$version"
    - id: resolve-name
      run: |
        name="$(basename ${{steps.find-cabal.outputs.file}} .cabal)"
        echo "::set-output name=name::$name"
