name: Extract metadata about a Cabal project

outputs:
  cabal-path: 
    description: Path to the cabal file
    value: ${{steps.find-cabal.outputs.file}}
  name:
    description: Package name
    value: ${{steps.resolve-name.outputs.name}}
  version:
    description: Package version
    value: ${{steps.resolve-version.outputs.version}}

runs:
  using: composite
  steps:
    - id: find-cabal
      shell: bash
      run: |
        files=(*.cabal)
        if [ "${#files[@]}" -ne 1 ]
        then
          echo "More than 1 cabal file"
          exit 1
        fi
        file=${files[0]}
        echo "::set-output name=file::$file"
    - id: resolve-version
      shell: bash
      run: |
        version="$(grep -oP '^version:\s*\K.*' ${{steps.find-cabal.outputs.file}})"
        echo "::set-output name=version::$version"
    - id: resolve-name
      shell: bash
      run: |
        name="$(basename ${{steps.find-cabal.outputs.file}} .cabal)"
        echo "::set-output name=name::$name"
